#!/bin/bash

tag=$GIT_BRANCH.$(git rev-parse --short HEAD).$(date -u +"%Y-%m-%dT%H-%M-%SZ")
docker tag $IMAGE_NAME $DOCKER_REPO:$tag
docker push $DOCKER_REPO:$tag

version=0.14.12.4
docker tag $IMAGE_NAME $DOCKER_REPO:$version

docker push $DOCKER_REPO:$version
