#!/bin/bash

docker tag $IMAGE_NAME $DOCKER_REPO:$(git rev-parse --short HEAD)
docker push $DOCKER_REPO:$(git rev-parse --short HEAD)

docker tag $IMAGE_NAME $DOCKER_REPO:$(date -u +"%Y-%m-%dT%H-%M-%SZ")
docker push $DOCKER_REPO:$(date -u +"%Y-%m-%dT%H-%M-%SZ")
