name: Publish Docker image
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@master
      - name: Define variables
        id: var
        shell: bash
        run: |
          echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_REPOSITORY }}:latest
            ${{ secrets.DOCKER_REPOSITORY }}:${{ env.GIT_BRANCH }}
            ${{ secrets.DOCKER_REPOSITORY }}:${{ env.GIT_BRANCH }}-${{ env.GIT_SHA }}
